### PR TITLE
Wait for 2 minutes while trying to obtain lock on a sync

### PR DESCRIPTION
**Pull request by raphyduck**
When they are several clients for a same master with automatic cron sync, sync can fail systematically on some clients if the cron jobs are set at the same time. Rather the trying to fit all the clients in different time slots, we can try several time to acquire a lock until a certain time has passed or the lock is acquired.

### CODE REVIEW

**Comment by greezybacon** [comment]
Thanks for the pull request. I like the idea. I'm nervous about the blanket time of two minutes though. Should we add a `-w/--wait` option to wait for the two minutes?

**Comment by raphyduck** [comment]
Good idea, I'll take care of that shortly :)

**Comment by torfason** [comment]
I agree with Jared about doing this as an option (-w/--wait). Best of all would be to do it as a configurable option, say, specify the number of seconds to wait (-w120/--wait=120). Two minutes is somewhat arbitrary and may be too short for some use-cases and to long for others. That way the wait time could be specified directly in the script/cron job, by someone who knows the specific use case.

**Comment by raphyduck** [comment]
Ok I made the requested changes. Please note that I am reinforcing the dependency on bash by using the internal bash variable $SECONDS. If you prefer that I make the script a bit less bash-dependent let me know.
And if you need any changes let me also know.

**Pull request closed without merging**
